### ISSUE TITLE
Retrieve the token

### ISSUE THREAD

**Issue by l0u1sg** [ghrlt/kard-private-api#1]
Hi, I'm trying to do the same thing you did but in NodeJS module. I can do the authentication, but I can't find the operationName to get the token. Could you help me ?  (here is the link of my repo and the code extract):
[https://github.com/l0u1sg/kard-bank-api](https://github.com/l0u1sg/kard-bank-api)
```
let TOKEN
        Axios.post('https://api.kard.eu/graphql'), {
            operationName: ""
        }
```

**Comment by ghrlt** [comment]
Hey! 
I'm posting this
```
payload = "{\"query\":\"mutation androidSignIn($authenticationProvider: AuthenticationProviderInput,$passcode: String!, $phoneNumber: PhoneNumber!, $vendorIdentifier: String!) { signIn(input: {authenticationProvider: $authenticationProvider,passcode: $passcode, phoneNumber: $phoneNumber, vendorIdentifier: $vendorIdentifier}) { accessToken refreshToken errors { path message } }}\",\"variables\":{\"passcode\":\""+code+"\",\"phoneNumber\":\""+num+"\",\"vendorIdentifier\":\""+VENDORIDENTIFIER+"\"},\"extensions\":{}}"
```
to get the Token in  `data['data']['signIn']['accessToken']`

Read it line 144, in login function
